name: .NET5.0

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Install dependencies
      run: |
       cd src/MusicInfoCompletion.Server
       dotnet restore
    - name: Build
      run: |
       cd src/MusicInfoCompletion.Server
       dotnet build --configuration Release --no-restore
    - name: Test
      run: |
       cd src/MusicInfoCompletion.Test
       dotnet test --verbosity normal
